# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='labels',
            field=models.CharField(default='', max_length=150, verbose_name='标签'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
