# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite_friend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='favorite',
        ),
    ]
