# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dissertation', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=20)),
                ('journal_date', models.CharField(max_length=10)),
                ('keywords', models.CharField(max_length=90)),
                ('dissertation_en', models.CharField(max_length=150)),
                ('abstract', models.CharField(max_length=1000)),
                ('author_unit', models.CharField(max_length=255)),
                ('author_contact', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=20)),
                ('keywords_en', models.CharField(max_length=800)),
                ('fund_project', models.CharField(max_length=255)),
                ('abstract_en', models.CharField(max_length=2000)),
                ('author_en', models.CharField(max_length=100)),
                ('journal_en', models.CharField(max_length=100)),
                ('url_id', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'papers',
            },
        ),
    ]
