# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recommended_papers', models.CharField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'recommended',
            },
        ),
    ]
