# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180326_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_wanfangid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
